DROP TABLE IF EXISTS USER;
CREATE TABLE USER AS SELECT * FROM CSVREAD('src/main/resources/csv/사용자.csv');

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT AS SELECT * FROM CSVREAD('src/main/resources/csv/계좌.csv');

DROP TABLE IF EXISTS ACCOUNT_HST;
CREATE TABLE ACCOUNT_HST AS SELECT * FROM CSVREAD('src/main/resources/csv/계좌내역.csv');